import type { Tod } from "@/lib/tod";

// "Picture of the day": a pixel landscape generated by rules (no image model). The day
// gives the seed (mountains, clouds, where the moon sits); the mind's mood sets the
// weather; the hour sets the light; the number of voices fills the village with lit
// windows; and the mind's stage decides how tall the tree of the mind has grown.
export interface SceneOpts {
  seed: number;
  phase: Tod;
  mood: string;
  voices: number; // claimed cells
  total: number;
  stage: number; // 0..5
  animated: boolean;
}

const SKY: Record<Tod, [string, string, string]> = {
  dawn: ["#2a1a4a", "#c8608a", "#ffb27a"],
  day: ["#3a7ed0", "#79c0ee", "#cdeeff"],
  dusk: ["#1a1246", "#9a4a9a", "#ff8a6c"],
  night: ["#03041a", "#0c1040", "#231a58"],
};
const FAR: Record<Tod, string> = { dawn: "#5a3a6a", day: "#5a7fb0", dusk: "#4a2a6a", night: "#12173f" };
const NEAR: Record<Tod, string> = { dawn: "#33224a", day: "#2f5a78", dusk: "#26164a", night: "#0a0e2c" };
const WATER: Record<Tod, [string, string]> = { dawn: ["#b6688c", "#3a2452"], day: ["#8ccff2", "#2c6a9a"], dusk: ["#c06a8a", "#221450"], night: ["#1a2260", "#05061c"] };
const LEAF: Record<Tod, string> = { dawn: "#5b8f6a", day: "#3f9a5e", dusk: "#6b5a9a", night: "#2f3f8a" };

function mulberry(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const hex2 = (h: string) => {
  const n = parseInt(h.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};
const mix = (a: string, b: string, k: number) => {
  const A = hex2(a);
  const B = hex2(b);
  return `rgb(${Math.round(A[0] + (B[0] - A[0]) * k)},${Math.round(A[1] + (B[1] - A[1]) * k)},${Math.round(A[2] + (B[2] - A[2]) * k)})`;
};

function disc(ctx: CanvasRenderingContext2D, cx: number, cy: number, r: number) {
  for (let y = -Math.ceil(r); y <= Math.ceil(r); y++) {
    const w = Math.floor(Math.sqrt(Math.max(0, r * r - y * y)));
    ctx.fillRect(Math.round(cx - w), Math.round(cy + y), w * 2 + 1, 1);
  }
}

const CLOUDS: Record<string, number> = { curious: 2, watching: 5, listening: 4, wondering: 4, restless: 3 };

export function drawScene(ctx: CanvasRenderingContext2D, W: number, H: number, t: number, o: SceneOpts) {
  const rnd = mulberry(o.seed);
  const u = Math.max(0.6, H / 100);
  const hz = Math.round(H * 0.62);
  const night = o.phase === "night";
  const sky = SKY[o.phase];
  const anim = o.animated ? t : 0;

  // sky
  for (let y = 0; y < hz; y++) {
    const k = y / hz;
    ctx.fillStyle = k < 0.5 ? mix(sky[0], sky[1], k * 2) : mix(sky[1], sky[2], (k - 0.5) * 2);
    ctx.fillRect(0, y, W, 1);
  }

  // stars
  const starA = night ? 1 : o.phase === "day" ? 0 : 0.5;
  for (let i = 0; i < 46; i++) {
    const x = Math.floor(rnd() * W);
    const y = Math.floor(rnd() * hz * 0.72);
    const ph = rnd() * 6.28;
    if (starA > 0) {
      ctx.globalAlpha = starA * (0.5 + 0.5 * Math.sin(anim / 500 + ph));
      ctx.fillStyle = i % 5 === 0 ? "#bfe6ff" : "#ffffff";
      ctx.fillRect(x, y, 1, 1);
    }
  }
  ctx.globalAlpha = 1;

  // aurora when the mind wonders (or once it has awakened), after dark
  if ((o.mood === "wondering" || o.stage >= 5) && (night || o.phase === "dusk")) {
    const ph = rnd() * 6;
    for (let x = 0; x < W; x++) {
      const y0 = hz * 0.3 + Math.sin(x * 0.07 + anim / 1700 + ph) * hz * 0.07;
      const h = hz * (0.13 + 0.04 * Math.sin(x * 0.11 + anim / 900));
      const g = ctx.createLinearGradient(0, y0, 0, y0 + h);
      g.addColorStop(0, "rgba(120,255,190,0)");
      g.addColorStop(0.5, "rgba(120,255,190,0.32)");
      g.addColorStop(1, "rgba(214,116,220,0)");
      ctx.fillStyle = g;
      ctx.fillRect(x, y0, 1, h);
    }
  }

  // sun / moon
  const cx = W * (0.18 + rnd() * 0.5);
  let cy = hz * 0.22;
  if (night) {
    ctx.fillStyle = "#f2f0ff";
    disc(ctx, cx, cy, Math.max(2, u * 4.2));
    ctx.fillStyle = mix(sky[0], sky[1], 0.2); // a bite out of it: the phase
    disc(ctx, cx + u * (1.2 + rnd() * 2.2), cy - u * 0.6, Math.max(2, u * 3.7));
  } else {
    cy = o.phase === "day" ? hz * 0.24 : hz * 0.78;
    const g = ctx.createRadialGradient(cx, cy, 0, cx, cy, u * 16);
    g.addColorStop(0, o.phase === "day" ? "rgba(255,244,190,0.55)" : "rgba(255,170,120,0.5)");
    g.addColorStop(1, "rgba(255,200,120,0)");
    ctx.fillStyle = g;
    ctx.fillRect(cx - u * 16, cy - u * 16, u * 32, u * 32);
    ctx.fillStyle = o.phase === "day" ? "#fff7c8" : "#ffd6a0";
    disc(ctx, cx, cy, Math.max(2, u * 5));
  }

  // clouds (mood decides how many)
  const nc = CLOUDS[o.mood] ?? 3;
  ctx.fillStyle = night ? "rgba(90,80,150,0.4)" : o.phase === "day" ? "rgba(255,255,255,0.85)" : "rgba(255,190,200,0.6)";
  for (let i = 0; i < nc; i++) {
    const w = W * (0.16 + rnd() * 0.14);
    const y = hz * (0.1 + rnd() * 0.42);
    const x = ((rnd() * (W + w) + anim * 0.004 * (0.6 + i * 0.25)) % (W + w)) - w;
    ctx.fillRect(Math.round(x), Math.round(y), Math.round(w), Math.max(1, Math.round(u * 2.2)));
    ctx.fillRect(Math.round(x + w * 0.18), Math.round(y - u * 1.4), Math.round(w * 0.5), Math.max(1, Math.round(u * 1.6)));
  }

  // two ranges of mountains
  const a1 = rnd() * 6;
  const a2 = rnd() * 6;
  const ridge = (x: number, amp: number, a: number, f: number) => hz * (amp + 0.07 * Math.sin(x * f + a) + 0.045 * Math.sin(x * f * 2.3 + a * 1.7));
  ctx.fillStyle = FAR[o.phase];
  for (let x = 0; x < W; x++) {
    const h = ridge(x, 0.13, a1, 0.05);
    ctx.fillRect(x, Math.round(hz - h), 1, Math.round(h));
  }
  ctx.fillStyle = NEAR[o.phase];
  for (let x = 0; x < W; x++) {
    const h = ridge(x, 0.05, a2, 0.09) * 0.7;
    ctx.fillRect(x, Math.round(hz - h), 1, Math.round(h));
  }

  // water, with the light of the sky and a shimmer
  const w0 = WATER[o.phase];
  for (let y = hz; y < H; y++) {
    ctx.fillStyle = mix(w0[0], w0[1], (y - hz) / Math.max(1, H - hz));
    ctx.fillRect(0, y, W, 1);
  }
  ctx.fillStyle = night ? "rgba(230,230,255,0.5)" : "rgba(255,255,255,0.45)";
  for (let y = hz + 1; y < H; y += 2) {
    const off = Math.sin(y * 0.9 + anim / 700) * u * 1.2;
    const near = Math.abs(off) < u * 0.9 ? 1 : 0;
    if (near) ctx.fillRect(Math.round(cx + off * 2 - u), y, Math.max(1, Math.round(u * 2)), 1);
    ctx.fillRect(Math.round(((y * 13.7 + anim / 60) % (W + 6)) - 6), y, Math.max(2, Math.round(u * 2.4)), 1);
  }

  // the village on the shore: one house per few voices, windows lit after dark
  const ratio = o.total > 0 ? Math.min(1, o.voices / o.total) : 0;
  const houses = o.voices > 0 ? Math.min(26, 1 + Math.round(ratio * 24)) : 0;
  const treeX = W * 0.76;
  const lit = night ? 1 : o.phase === "dusk" ? 0.8 : o.phase === "dawn" ? 0.4 : 0.05;
  for (let i = 0; i < houses; i++) {
    const w = Math.max(2, Math.round(u * (2.4 + rnd() * 2.2)));
    const h = Math.max(2, Math.round(u * (2 + rnd() * 2.6)));
    let x = Math.round(((i + 0.5) / houses) * (W - w) + (rnd() - 0.5) * u * 3);
    if (Math.abs(x - treeX) < u * 9) x = Math.round(x - u * 12 * (x < treeX ? 1 : -1));
    x = Math.max(0, Math.min(W - w, x));
    ctx.fillStyle = NEAR[o.phase];
    ctx.fillRect(x, hz - h, w, h);
    ctx.fillRect(x - 1, hz - h - 1, w + 2, 1);
    ctx.fillRect(x, hz - h - 2, w, 1);
    if (rnd() < lit * (0.5 + ratio * 0.5)) {
      ctx.fillStyle = "#ffd166";
      ctx.fillRect(x + Math.floor(w / 2), hz - Math.ceil(h * 0.6), 1, 1);
    }
  }

  // the tree of the mind: how tall it is says how grown the mind is
  const tr = [0, 0.06, 0.1, 0.15, 0.2, 0.26][o.stage] * H;
  if (o.stage === 0) {
    ctx.fillStyle = "#c4f260";
    ctx.globalAlpha = 0.5 + 0.5 * Math.sin(anim / 400);
    ctx.fillRect(Math.round(treeX), hz - 2, 1, 2);
    ctx.globalAlpha = 1;
  } else {
    const trunkH = Math.max(2, Math.round(tr));
    ctx.fillStyle = "#4a3a2a";
    ctx.fillRect(Math.round(treeX), hz - trunkH, Math.max(1, Math.round(u * (0.6 + o.stage * 0.3))), trunkH);
    const cr = Math.max(2, u * (1.6 + o.stage * 1.8));
    if (o.stage >= 5) {
      const g = ctx.createRadialGradient(treeX, hz - trunkH - cr * 0.3, 0, treeX, hz - trunkH - cr * 0.3, cr * 3.4);
      g.addColorStop(0, "rgba(196,242,96,0.32)");
      g.addColorStop(1, "rgba(196,242,96,0)");
      ctx.fillStyle = g;
      ctx.fillRect(treeX - cr * 3.5, hz - trunkH - cr * 3.7, cr * 7, cr * 7);
    }
    ctx.fillStyle = LEAF[o.phase];
    const sway = Math.sin(anim / 1200) * u * 0.4;
    for (let k = 0; k < 5; k++) {
      const dx = (k - 2) * cr * 0.55 + sway * (k % 2 ? 1 : -1);
      const dy = -Math.abs(k - 2) * cr * 0.35;
      disc(ctx, treeX + dx, hz - trunkH + dy - cr * 0.4, cr * (k === 2 ? 1 : 0.75));
    }
    // leaves that glow: one for every few voices
    const glows = Math.min(40, Math.round(ratio * 40) + o.stage * 2);
    ctx.fillStyle = "#c4f260";
    for (let k = 0; k < glows; k++) {
      const ang = rnd() * 6.28;
      const rad = rnd() * cr * 1.5;
      ctx.globalAlpha = night || o.phase === "dusk" ? 0.5 + 0.5 * Math.sin(anim / 400 + k) : 0.25;
      ctx.fillRect(Math.round(treeX + Math.cos(ang) * rad), Math.round(hz - trunkH - cr * 0.6 + Math.sin(ang) * rad * 0.7), 1, 1);
    }
    ctx.globalAlpha = 1;
  }

  // weather, from the mood
  if (o.mood === "listening") {
    ctx.fillStyle = "rgba(160,210,255,0.55)";
    for (let i = 0; i < 30; i++) {
      const x = (rnd() * W + anim * 0.02 + i * 3) % W;
      const y = (rnd() * H + anim * 0.09) % H;
      ctx.fillRect(Math.round(x), Math.round(y), 1, 3);
    }
  } else if (o.mood === "watching") {
    for (let i = 0; i < 3; i++) {
      const g = ctx.createLinearGradient(0, 0, W, 0);
      const s = ((anim * 0.01 * (i + 1) * 0.3) % 100) / 100;
      g.addColorStop(0, "rgba(255,255,255,0)");
      g.addColorStop(Math.min(0.99, 0.2 + s * 0.6), "rgba(255,255,255,0.22)");
      g.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = g;
      ctx.fillRect(0, hz - u * (3 + i * 3), W, u * 4);
    }
  } else if (o.mood === "restless") {
    ctx.fillStyle = "rgba(255,255,255,0.35)";
    for (let i = 0; i < 12; i++) {
      const y = rnd() * hz * 0.9;
      const x = ((rnd() * (W + 20) + anim * 0.09 * (1 + i * 0.1)) % (W + 20)) - 10;
      ctx.fillRect(Math.round(x), Math.round(y), Math.max(3, Math.round(u * 5)), 1);
    }
  } else if (o.mood === "curious" && o.stage >= 1) {
    ctx.fillStyle = "#c4f260";
    for (let i = 0; i < 8; i++) {
      const bx = treeX + (rnd() - 0.5) * u * 26;
      const by = hz - u * (4 + rnd() * 10);
      ctx.globalAlpha = 0.4 + 0.6 * Math.abs(Math.sin(anim / 500 + i * 1.3));
      ctx.fillRect(Math.round(bx + Math.sin(anim / 800 + i) * u * 2), Math.round(by + Math.cos(anim / 700 + i) * u), 1, 1);
    }
    ctx.globalAlpha = 1;
  }
}

// One number per calendar day (local), so everyone sees the same landscape on the same day.
export function daySeed(d = new Date()): number {
  return d.getFullYear() * 10000 + (d.getMonth() + 1) * 100 + d.getDate();
}
